version: "3.7"
services:
  client-envoy:
    build:
      context: .
      dockerfile: Dockerfile-client
    hostname: client
    ports:
      - 8001:8001
    networks:
      - envoymesh
  backend-local-1:
    build:
      context: .
      dockerfile: Dockerfile-server
    environment:
      - HOST=bk-local-1
    hostname: bk-local-1
    networks:
      - envoymesh
  backend-local-2:
    build:
      context: .
      dockerfile: Dockerfile-server
    environment:
      - HOST=bk-local-2
    hostname: bk-local-2
    networks:
      - envoymesh
  backend-remote:
    build:
      context: .
      dockerfile: Dockerfile-server
    environment:
      - HOST=bk-remote
    hostname: bk-remote
    networks:
      - envoymesh

networks:
  envoymesh: {}