version: "3.7"
services:
  client-envoy:
    build:
      context: .
      dockerfile: Dockerfile-client
    # image: curlimages/curl
    # command: sleep 10000
    hostname: client
    networks:
      - envoymesh
  backend-local-1:
    build:
      context: .
      dockerfile: Dockerfile-server
    environment:
      - HOST=bk-local-1
    hostname: bk-local-1
    networks:
      - envoymesh
  backend-local-2:
    build:
      context: .
      dockerfile: Dockerfile-server
    environment:
      - HOST=bk-local-2
    hostname: bk-local-2
    networks:
      - envoymesh
  backend-remote:
    build:
      context: .
      dockerfile: Dockerfile-server
    environment:
      - HOST=bk-remote
    hostname: bk-remote
    networks:
      - envoymesh

networks:
  envoymesh: {}